name: Extract boot / init_boot.img

on:
  workflow_dispatch:
    inputs:
      rom_ver:
        description: 'ROM Version'
        required: true
      rom_url:
        description: 'ROM Link'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230425/lineage-19.1-20230425-nightly-tissot-signed.zip'


jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo apt install aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto
          pip install protobuf==3.20
          BUILD_TIME=$(TZ=Asia/Kolkata date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: Extract the image and upload it to TMP
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          cd ${{ github.workspace }}
          touch info.md
          echo "ROM Version: ${{ github.event.inputs.rom_versiom }}" >> info.md
          echo "Submission date：$(TZ=Asia/Kolkata date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM Download direct link：${{ github.event.inputs.rom_url }}" >> info.md
          cd ~/Firmware_extractor/out
          if [ -f "init_boot.img" ]; then rm boot.img; fi
          du -h --total *.img | sed 's/^/Extract image size： /' | head -n 1 >> ${{ github.workspace }}/info.md

      - name: Upload images and related information
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/Firmware_extractor/out/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}

